Naming classes guidelines
hihaho/phpstan-rules pull request #1
Opened 2023-09-22 08:02 UTC by RobertBoes

This PR implements the following guidelines:

- https://guidelines.hihaho.com/laravel.html#commands
- https://guidelines.hihaho.com/laravel.html#resources
- https://guidelines.hihaho.com/laravel.html#mailables
- https://guidelines.hihaho.com/laravel.html#notifications

2023-09-22 09:37 UTC, Treggats requested changes

2023-09-22 09:37 UTC, Treggats commented on src/Rules/NamingClasses/SuffixableRule.php
> +        ReflectionProvider $reflectionProvider
```suggestion
        ReflectionProvider $reflectionProvider,
```

2023-09-22 09:37 UTC, Treggats commented on src/Rules/NamingClasses/SuffixableRule.php
> + * @implements \PHPStan\Rules\Rule<\PhpParser\Node\Stmt\Class_>
Bit weird classname, but hey 🤷

2023-09-22 09:37 UTC, Treggats commented on tests/Rules/NamingClasses/stubs/commands/Base.php
> +<?php
```suggestion
<?php declare(strict_types = 1);
```

2023-09-22 09:37 UTC, Treggats commented on tests/Rules/NamingClasses/stubs/commands/FromBaseCommand.php
> +<?php
```suggestion
<?php declare(strict_types = 1);
```

2023-09-22 09:37 UTC, Treggats commented on tests/Rules/NamingClasses/stubs/commands/FromBaseWithoutSuffix.php
> +<?php
```suggestion
<?php declare(strict_types = 1);
```

2023-09-22 09:37 UTC, Treggats commented on tests/Rules/NamingClasses/stubs/commands/NotifyUsers.php
> +<?php
```suggestion
<?php declare(strict_types = 1);
```

2023-09-22 09:37 UTC, Treggats commented on tests/Rules/NamingClasses/stubs/commands/SendMailCommand.php
> +<?php
```suggestion
<?php declare(strict_types = 1);
```

2023-09-22 09:37 UTC, Treggats commented on tests/Rules/NamingClasses/stubs/mail/AccountActivated.php
> +<?php
```suggestion
<?php declare(strict_types = 1);
```

2023-09-22 09:37 UTC, Treggats commented on tests/Rules/NamingClasses/stubs/mail/AccountActivatedMail.php
> +<?php
```suggestion
<?php declare(strict_types = 1);
```

2023-09-22 09:37 UTC, Treggats commented on tests/Rules/NamingClasses/stubs/notification/ResetPassword.php
> +<?php
```suggestion
<?php declare(strict_types = 1);
```

2023-09-22 09:37 UTC, Treggats commented on tests/Rules/NamingClasses/stubs/notification/ResetPasswordNotification.php
> +<?php
```suggestion
<?php declare(strict_types = 1);
```

2023-09-22 09:37 UTC, Treggats commented on tests/Rules/NamingClasses/stubs/resources/RandomFile.php
> +<?php
```suggestion
<?php declare(strict_types = 1);
```

2023-09-22 09:37 UTC, Treggats commented on tests/Rules/NamingClasses/stubs/resources/Video.php
> +<?php
```suggestion
<?php declare(strict_types = 1);
```

2023-09-22 09:37 UTC, Treggats commented on tests/Rules/NamingClasses/stubs/resources/VideoResource.php
> +<?php
```suggestion
<?php declare(strict_types = 1);
```

2023-09-22 09:43 UTC, Treggats approved these changes

2023-11-07 16:38 UTC, SanderMuller approved these changes

2023-11-22 12:02 UTC, merged