Feature: Disallow facade alias in code
hihaho/phpstan-rules pull request #18
Opened 2024-05-01 11:59 UTC by RobertBoes

Only allows facade alias to be used in `.blade.php` files

2024-05-01 12:05 UTC, Treggats requested changes

2024-05-01 12:05 UTC, Treggats commented on tests/Rules/stubs/CustomFacade.php
> +<?php
consistency
```suggestion
<?php declare(strict_types=1);
```

2024-05-01 16:55 UTC, SanderMuller approved these changes

2024-05-02 09:59 UTC, Treggats approved these changes
I'm not going to be an ass about the missing EOL 😋

2024-05-02 10:06 UTC, merged